---
driver:
  name: docker
  hostname: kitchen-salt.ci.local
  use_sudo: true

provisioner:
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  #require_chef: false
  vendor_repo:
    apt:
      url: http://apt.tcpcloud.eu
      key_url: http://apt.tcpcloud.eu/public.gpg
      components: salt
  dependencies:
    - path: apt
      name: linux
  grains:
    noservices: True
    
#platforms:
#- name: centos-6.6
#- name: ubuntu-14.04
