---
driver:
  name: docker
  hostname: instance.ci.local
  use_sudo: false

provisioner:
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: 2016.3.0
  grains:
    noservices: True
    
#platforms:
#- name: centos-6.6
#- name: ubuntu-14.04
