language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - ruby-head

script: bundle exec rspec

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: true

bundler_args: --without='vagrant'

#before_script:
# - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)

install:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)
  - pwd
  - FORMULA=salt-formula-postfix
  - git clone https://github.com/salt-formulas/$FORMULA.git --branch master --single-branch ../$FORMULA
  #- git clone https://github.com/simonmcc/beaver-formula.git --branch test-kitchen --single-branch ../beaver-formula
  - test -e ../$FORMULA/.kitchen.docker.yml || cp .kitchen.docker.yml ../$FORMULA
  - test -e ../$FORMULA/Rakefile || cp Rakefile ../$FORMULA
  - cp -f Gemfile ../$FORMULA
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - cd ../$FORMULA
  #- export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --without='vagrant'
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen list

script:
  # Run test-kitchen with docker driver:
  - pwd
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen test
  #- travis_retry bundle exec rake integration:docker


after_script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen list
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen destroy all
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen diagnose --all



after_failure: cat docker_daemon.log
