language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - ruby-head

script: bundle exec rspec

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: true

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)


install:
  - pwd
  - git clone https://github.com/simonmcc/beaver-formula.git --branch test-kitchen --single-branch ../beaver-formula
  - cd ../beaver-formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install
  - bundle exec kitchen list

script:
# Run test-kitchen with docker driver, for example:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen test


after_script:
  - bundle exec kitchen list
  - bundle exec kitchen destroy all
  - bundle exec kitchen diagnose --all
